### ISSUE TITLE
Hide keyboard

### ISSUE THREAD

**Issue by florianhenonin** [cjwirth/RichEditorView#103]
How hide keyboard on return key pressed ?

Thank you for your work.

**Comment by Rashesh-Bosamiya** [comment]
you can add `Dismiss` button on Keyboard Toolbar.

```
let itemDone = RichEditorOptionItem(image: nil, title: "Done") { (toolBar) in
            self.view.endEditing(true)
        }

var options = toolbar.options
options.append(itemDone)
toolbar.options = options
```

**Comment by cjwirth** [comment]
Assuming you mean the "return" button on the keyboard -- no, I currently don't have any support for this.

What you will want to do though, is set up a listener for keyboard presses in the JS. If the user presses return, you should be able to dismiss the keyboard from that method.

Or, as Rashesh-Bosamiya says, add a done button to the toolbar!
