### ISSUE TITLE
Swift-3 (IOS 10.2) Support

### ISSUE THREAD

**Issue by RamChandraNagalapelli** [cjwirth/RichEditorView#104]
Pods are not supporting for swift3(IOS 10.2)
showing 100+ errors after pod installation

**Comment by cjwirth** [comment]
You're right, CocoaPods is pointing towards and old version.

I have recently merged Swift 3 support into the master branch, and will be releasing the new version on CocoaPods soon.

**Comment by chaoticbit** [comment]
@RamChandraNagalapelli Same here just now installed for iOS 10.2 Swift 3. 
Showing 126 errors 
![screen shot 2017-03-09 at 3 24 05 pm](https://cloud.githubusercontent.com/assets/6007217/23745040/c55ff930-04dc-11e7-9ce1-4ee019acc2a2.png)

Can you please release the new version soon?

**Comment by moonorblue** [comment]
@RamChandraNagalapelli @chaoticbit 
You can use the Swift 3 version by use the master branch directly for now
like this
```
pod 'RichEditorView', :git => "https://github.com/cjwirth/RichEditorView.git", :branch => "master"
```

**Comment by chaoticbit** [comment]
@moonorblue Yes. Tried that and it's working. Thanks
