### ISSUE TITLE
Adding word limit

### ISSUE THREAD

**Issue by n1tesh** [cjwirth/RichEditorView#113]
Is it possible to add word limit to this? Like we can do in textView didChange.

**Comment by cjwirth** [comment]
Hey! That's a pretty good idea :bulb: 

What I would suggest is doing something like hooking into the delegate method for when the content changes, and then setting the content to be within your constraints.

Something like this:

```
func richEditor(_ editor: RichEditorView, contentDidChange content: String) {
    editor.text = content[..<limit]
}
```

That code won't run for a few reasons, but it should give you a basic idea.

If you need more control, for example, if you need to load more JS or CSS into the webview, you can do something like [I describe in a previous issue](https://github.com/cjwirth/RichEditorView/issues/43) about loading custom resources into the web view. Then you could do whatever you want, I guess.

**Comment by n1tesh** [comment]
@cjwirth Is there any way to add delegates like 'shouldChangeTextInRange' or 'shouldChangeCharactersIn' ?
