### ISSUE TITLE
Objective-C only

### ISSUE THREAD

**Issue by ElKnarzo** [cjwirth/RichEditorView#114]
HI,

I've been looking for a framework just like this one. I have found the ZSSRichTextEditor, but this is less suitable for my project. Because I want to integrate the RcihTextEditor into a table cell. This is not possible for the ZSSRichTextEditor and I have encountered this framework.

My question: Is there a variant only for Objective-C?

**Comment by cjwirth** [comment]
Apart from just a few things, you should be able to use the RichEditorView in a project that is all Objective-C. Check out the sample project where I have an example of using it in an Objective-C View Controller.
