### ISSUE TITLE
Support for tintColor

### ISSUE THREAD

**Issue by EmperiorEric** [cjwirth/RichEditorView#121]
`UITextField` and `UITextView` both allow setting a `tintColor` to adjust the caret and text selection handle colors. For `RichEditorView` to fit in better with the stand UIKit elements, it would be helpful for `RichEditorView` respond to tintColor in the same fashion.

**Comment by cjwirth** [comment]
I'm not sure this is currently possible 😞 

- [::selection](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection) wasn't working
- [caret-color](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color) also seems unsupported
- [This guy couldn't figure it out.](https://twitter.com/calendee/status/657654840563077120)

I really like this idea and I'd like to support it, but I don't know how. Let me know if you find anything good, and we can reopen and fix it.
