### ISSUE TITLE
Please convert to swift 3

### ISSUE THREAD

**Issue by UmaMadhavi** [cjwirth/RichEditorView#122]
Hello @cjwirth . I want to import this library using pods . Can u please update to swift 3

**Comment by cjwirth** [comment]
I plan on getting around to this and Swift 4 over the weekend.
You should be able to use the `master` branch until then 👍

**Comment by kiranruth** [comment]
hey, @cjwirth 

Is the branch I can use ??

**Comment by cjwirth** [comment]
For anyone who comes looking -- I closed this issue because version 4.0.0 has been converted to Swift 3
