### ISSUE TITLE
new branch for swift 4

### ISSUE THREAD

**Issue by AlexanderZubkov** [cjwirth/RichEditorView#123]
Please make a separate branch for Swift 4
Now to download working code for xcode8 I had to:
pod 'RichEditorView', :git => "https://github.com/cjwirth/RichEditorView.git", :commit => '447e3b3'
that is not a good idea for getting a working code

PS Swift 3 brunch is outdated
PPS pod 'RichEditorView', '3.2.0' leads to Swift 3 brunch

**Comment by cjwirth** [comment]
> Now to download working code for xcode8 I had to:
pod 'RichEditorView', :git => "https://github.com/cjwirth/RichEditorView.git", :commit => '447e3b3'

I'm not sure why you would have to specify a commit? Why are you not using version 4.0.0 which is Swift 3?

> PS Swift 3 brunch is outdated

Very possible, there is a new release using Swift 3 now. Maybe I should update that branch as well.

**Comment by AlexanderZubkov** [comment]
for ex. version 4.0.0 uses @objcMembers that is not recognized by Swift 3

**Comment by cjwirth** [comment]
Did I screw up the tags? 

[Here is the RichEditorView.swift on 4.0.0](https://github.com/cjwirth/RichEditorView/blob/4.0.0/RichEditorView/Classes/RichEditorView.swift#L40) -- it doesn't have @objcMembers.

[Here's the same class on the current `master` branch](https://github.com/cjwirth/RichEditorView/blob/master/RichEditorView/Classes/RichEditorView.swift#L40) -- Here I have already updated to Swift 4, yes. But that's not the 4.0.0 release.

**Comment by AlexanderZubkov** [comment]
cjwirth sorry!

Because of sticking up to master branch to get the latest from it I forgot to try without it...

**Comment by cjwirth** [comment]
Not a problem! I know a lot of places use the master branch to be "the most up to date, good state of things to use." Maybe I should do that too, so there wouldn't be this kind of confusion!
