### ISSUE TITLE
Strange horizontal line at the end of editor view

### ISSUE THREAD

**Issue by chirayu25** [cjwirth/RichEditorView#126]
![simulator screen shot 06-jul-2017 11 24 13 pm](https://user-images.githubusercontent.com/2736902/27925396-3e54d4be-62a2-11e7-8cb5-3926143b69e3.png)

**Comment by cjwirth** [comment]
I'm not sure where that's coming from. Do you have a sample to reproduce it?

**Comment by chirayu25** [comment]
Sample? Not sure what you are trying to say.

**Comment by cjwirth** [comment]
How do you get that bug to appear? How should I reproduce the bug, so that I can try and fix it? It would be super helpful if you could make a sample app that has the bug in it that I could play with.

**Comment by chirayu25** [comment]
I added richTextView in a tableViewCell. 

Code in viewController is a follows:

      
```
   cell.contentRichEditorView.delegate = self
            cell.contentRichEditorView.focus()
            cell.contentRichEditorView.inputAccessoryView = toolbar
```
    

```
 toolbar.delegate = self
            toolbar.editor =  cell.contentRichEditorView
            cell.contentRichEditorView.html = contentText
```

**Comment by cjwirth** [comment]
OK thanks that will help out. What kind of text are you putting into the HTML?

**Comment by chirayu25** [comment]
I am using same view for add and edit

RichTextView shall be blank of shall be filled with html text or non-html text on load.

**Comment by chirayu25** [comment]
@cjwirth Any update on this?

**Comment by cjwirth** [comment]
Sorry, no... 😞 

I probably don't give this project the love it deserves. I'm not using this in any of my current projects, and so I really only look at it occasionally on weekends.

**Comment by chirayu25** [comment]
It would be great if you can spare some time. Editor is boon to my project

**Comment by cjwirth** [comment]
I have a fix. What version are you using?

**Comment by chirayu25** [comment]
Thats great. I am running version 1.0

**Comment by cjwirth** [comment]
Really? You're using the version that was released in April 2015? You should probably update to one of the more recent versions.

**Comment by chirayu25** [comment]
Where can I find version?

**Comment by cjwirth** [comment]
What do you have in your `Podfile`, or `Podfile.lock`?

**Comment by chirayu25** [comment]
No I used manual method. But version is hardly 2-3 months old

**Comment by cjwirth** [comment]
Well OK. In that case I don't know how to figure out which version you're using. Anyway, I the fix is on the [fix-webview-line](https://github.com/cjwirth/RichEditorView/tree/fix-webview-line) branch. Or if you want to fix it manually, it's a pretty easy change:

```diff
// RichEditorView.swift
     private func setup() {
-        backgroundColor = .red
+        backgroundColor = .white

         webView.frame = bounds
         webView.delegate = self
@@ -143,7 +143,11 @@ open class RichEditorView: UIView, UIScrollViewDelegate, UIWebViewDelegate, UIGe
         webView.scalesPageToFit = false
         webView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
         webView.dataDetectorTypes = UIDataDetectorTypes()
-        webView.backgroundColor = .white
+
+        // These to are a fix for a bug where UIWebView would display a black line at the bottom of the view.
+        // https://stackoverflow.com/questions/21420137/black-line-appearing-at-bottom-of-uiwebview-how-to-remove
+        webView.backgroundColor = .clear
+        webView.isOpaque = false
```

**Comment by chirayu25** [comment]
Perfect solutions. Thanks @cjwirth

**Comment by cjwirth** [comment]
Glad it worked 👍

**Comment by ppamorim** [comment]
This is not a problem of the library code, any `UIWebView` instance does this.
