### ISSUE TITLE
Focus RichEditorView when view is tapped

### ISSUE THREAD

**Issue by Jirka1111** [cjwirth/RichEditorView#13]
How can I take a focus when I click on the REV window? For now, I can write to REV input view only if I click on the first row. I want to take a focus (start writing) after I click anywhere on the input view of REV.

Thanks for help.

**Comment by cjwirth** [comment]
This is a bit of a problem, isn't it? How I'm solving it in my problem is by adding a tap gesture recognizer to its superview (there is other tappable space that isn't just the REV). Then in the action that it calls, I call `richEditorView.focus()`.

I suppose that I could probably add a tap gesture recognizer directly on the REV so then it will automatically open when tapped anywhere on the view. (I wonder if this would cancel out other touch events that happen in the web view?)

**Comment by Jirka1111** [comment]
Dear cjwirth, do you have a solution on this problem?

Thank you.

**Comment by cjwirth** [comment]
Yeah, just like I said -- add a tap gesture recognizer that then focusses the editor when tapped. You'll also probably want to remove the gesture when the editor actually has focus, so you aren't receiving taps while editing.

A crude implementation might be like:

```Swift
class ViewController: UIViewController {
    ...
    override func viewDidLoad() {
        ...
        let tapGesture = UITapGestureRecognizer(target: self, action: Selector("focusEditorView"))
        tapGesture.delegate = self
        editorView.addGestureRecognizer(tapGesture)
    }

    func focusEditorView() {
        // You could do something better than this, like remove the 
        // gesture recognizer if it's not needed anymore 
       if editorView.runJS("document.hasFocus()") != "true" {
            editorView.focus()
        }
    }
}

extension ViewController: UIGestureRecognizerDelegate {
    // You need to make sure you receive the taps, 
    // because there are also gesture recognizers 
    // on the internal views in the UIWebView
    func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return true
    }
}
```

**Comment by cjwirth** [comment]
This is something I might like to add as a default feature, so I am keeping the ticket open. I'm still not sure on the best approach to removing or disabling the tap gesture recognizer while the web view is focussed.

**Comment by Jirka1111** [comment]
Thank you for your work on this ;)

**Comment by cjwirth** [comment]
Take a look at the [fix/focus-on-tap](https://github.com/cjwirth/RichEditorView/tree/fix/focus-on-tap) branch. Let me know if it works for you.

It's the approach I mentioned above, but instead of running JS, I am just checking to see if the web view has the first responder, and if not, focusing it.

**Comment by Jirka1111** [comment]
Dear cjwirth,
it works like a charm! 

Thank you very much.
