### ISSUE TITLE
Become first responder does not work.

### ISSUE THREAD

**Issue by PanagiotisVakalis** [cjwirth/RichEditorView#131]
Hello, I am using your library in order to handle HTML in my application. I have implemented a mention functionality when the user enters the '@' character. So, once the user has entered the mention character, a table view with a text field for search is being presented. The search text field is now the first responder. When a user from the table view is being tapped, the text field is being resigned and the whole mention view is being disappeared. 
The problem is that the editor is not being the first responder, even if I have called the becomeFirstResponder() function.

While I was trying to fix this I performed the following changes in the RichEditorView.swift:
I have overriden the canBecomeFirstResponder like this:
```
open override var canBecomeFirstResponder: Bool {
     return true
}
```
And the becomeFirstResponder like this:
```
open override function becomeFirstResponder() -> Bool {

     if !webView.containsFirstResponder {
          self.focus()
     }

     return true
}
```

but still it does not work.

How can I make the editor the first responder when the whole view containing the mention related elements is being disappeared?

Thank you in advance!! :) :)

**Comment by cjwirth** [comment]
I just added this functionality to master. It's pretty much the same funcitonality as you just added, so it seems weird that it's not working for you....? It works in the sample project.

You can also use `editorView.focus()` and `editorView.blur()` (which it looks like you already knew about!) if you just want to activate/deactivate the editor :)
