### ISSUE TITLE
Crashes at method : '- (void)setCjw_inputAccessoryView:(UIView *)view'  at category :'UIWebView (CJWHackishAccessoryHiding)'

### ISSUE THREAD

**Issue by Mehul18292** [cjwirth/RichEditorView#133]
I Just added RichEditroView in my project(implemented in swift) via pods. Now, Initializing RichEditorView, with given frame, makes app to crash.

The app is getting crashed at : 
line 29:
filename: CJWWebView+HackishAccessoryHiding.m
method: - (void)setCjw_inputAccessoryView:(UIView *)view 
line:  "object_setClass(browserView, hackishFixClass);" 

Also, After checking/debugging, i found that - hackishFixClass has value nil.

Can anyone please give me solution to this.

**Comment by cAibDe** [comment]
你是怎么解决的啊
