### ISSUE TITLE
Need mention and hashtag support like ZSSRichTextEditor

### ISSUE THREAD

**Issue by Mehul18292** [cjwirth/RichEditorView#135]
Hello @cjwirth : Can you please provide me the idea for adding mention and hashtag detection support similar to ZSSRichTextEditor.

**Comment by cjwirth** [comment]
I'm not really sure what this will take, but it's going to involve quite a bit of work, I would imagine. 

A while ago, I posted in an issue about [how to load custom CSS or JS into the editor](https://github.com/cjwirth/RichEditorView/issues/43). From there, you should be able to load whatever you want, add hooks, or do whatever you would normally do in the browser.
