### ISSUE TITLE
RichEditorView scrolls content over sibling views

### ISSUE THREAD

**Issue by M-HERBRICH-ITC** [cjwirth/RichEditorView#137]
I've the following problem:

-UIView
--- UILabel (created by info)
--- UILabel (title)
--- RichEditorView

When I scroll RichEditorView it scrolls the content over the other sibling elements.

Please see video!
![richeditorview_bug](https://user-images.githubusercontent.com/4866997/30123010-dc3eb596-9330-11e7-86a5-f72a459354b9.gif)

Anybody a solution?

**Comment by steviemo** [comment]
editorView.webView.clipsToBounds = true

**Comment by cjwirth** [comment]
> editorView.webView.clipsToBounds = true

Pretty sure this will work.

**Comment by M-HERBRICH-ITC** [comment]
@cjwirth Thank you so much, it works!
