### ISSUE TITLE
How to make RichEditorView become first responder ?

### ISSUE THREAD

**Issue by malonguwa** [cjwirth/RichEditorView#138]
How to make RichEditorView become first responder and the keyboard will pop up, just like what we did to textView.becomeFirstResponder()
Thanks a lot

**Comment by cjwirth** [comment]
I just added this to master :+1: 

You can also use the `editorView.focus()` to become first responder, or `editorView.blur()` to resign first responder.

**Comment by panychyk** [comment]
editorView.focus() - not work for me(

**Comment by IshuRocks** [comment]
editorView.focus() - not work for me (on iOS 16.0)
