### ISSUE TITLE
shouldChangeTextInRange:(NSRange) Delegate?

### ISSUE THREAD

**Issue by xiaosongshu** [cjwirth/RichEditorView#141]
Is there a way to implement a delegate similar to UITextView's 

> - (BOOL)textView:(UITextView *)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text

Using for autocorrect manipulation

**Comment by cjwirth** [comment]
This is something I wanted to add from the beginning. I don't think there is a good way to do it, unfortunately. The reason being that the JS callback doesn't get called until the text is already added in. Sorry!

If you come up with something that works well, I'd like to know, so feel free to open a pull request if you do.
