### ISSUE TITLE
Question: UIView supported?

### ISSUE THREAD

**Issue by magonicolas** [cjwirth/RichEditorView#145]
Does is support adding a custom UIView?

Bests!

**Comment by cjwirth** [comment]
Hey! Hope this code is helping you 😃 

Like any other UIView, you can manually `addSubview`, but I have no plans on making it support inline UIViews. The reason being that this is just a thin wrapper around a UIWebView, and I'm not really sure how you'd embed a UIView inside the HTML being displayed inside.

Sorry!
