### ISSUE TITLE
Toolbar scrolling issues on iOS 11

### ISSUE THREAD

**Issue by Thisura98** [cjwirth/RichEditorView#148]
When using the RichEditorToolbar inside an app that is running on iOS 11, various issues in regards to the toolbar scrollView length occur.

Such as,

- All items have loaded but the scrollView length is shorter than the cumulative widths of all items.

- Some items are missing and the scrollView length seems to fit the loaded number of elemtns.

- Elements at either ends of the toolbar shrink.

I have done some digging around in the library and found the following block of code to cause the issues. The code can be found inside RichEditorToolbar.swift/RichEditorToolbar/updateToolbar()

```
let defaultIconWidth: CGFloat = 22.0
let barButtonItemMargin: CGFloat = 11
let width: CGFloat = buttons.reduce(0) {sofar, new in
    if let view = new.value(forKey: "view") as? UIView {
        return sofar + view.frame.size.width + barButtonItemMargin
    } else {
        return sofar + (defaultIconWidth + barButtonItemMargin)
    }
}

```

I have found a temporary fix for this issue by changing the value '22.0' to '28.0' as per the item width obtained by running my code (and debugging) under iOS 10. However it would be awesom if you could fix this internally since my project depends on CocoaPods to maintain project dependencies.

I have linked below a stackoverflow page that is related to the issue I have just mentioned.

https://stackoverflow.com/questions/46773927/ios-11-cannot-access-uiview-of-uibarbutton

**Comment by zczc521** [comment]
Hi do you know how to recive the image click？

**Comment by jonajgs** [comment]
pull request for resolve this =)

**Comment by f0go** [comment]
Same here 😩

**Comment by cjwirth** [comment]
I just pushed this change to master. I will be putting out a release (5.0.0) later today that includes the change.

The toolbar is kind of a hacky view to begin with, it was made mainly as a demonstration; I wasn't expecting people to use it, because I thought people would want to have their own design in their apps.
