### ISSUE TITLE
Toolbar wrong size

### ISSUE THREAD

**Issue by fabiocberg** [cjwirth/RichEditorView#150]
Please, on your RichEditorToolbar.swift class, change the line 137 from:

`let defaultIconWidth: CGFloat = 22`

To:

`let defaultIconWidth: CGFloat = 28`

The wrong icon width is generating a wrong toolbar width, so it's not showing all icons.

Thanks.

**Comment by cjwirth** [comment]
This was just pushed to master. Check out some more info in the other issue: https://github.com/cjwirth/RichEditorView/issues/148
