### ISSUE TITLE
RichEditorView can't show text

### ISSUE THREAD

**Issue by dev4shane** [cjwirth/RichEditorView#17]
use the editor.setHTML function can't show the text from server, but can show the text in form just like in the readme text, it's weird, did I miss something??

**Comment by dev4shane** [comment]
and  editor.delegate = self can't be allowed in UIViewController, i'm a totally baby bird in ios, really needs help!

**Comment by cjwirth** [comment]
> use the editor.setHTML function can't show the text from server, but can show the text in form just like in the readme text, it's weird, did I miss something??

I'm not sure what you're trying to do? This library doesn't do anything with text from a server. In `setHTML`, you'll pass in some HTML that it will then display. For example, 
`this text is <b>bold</b> and such.` will become "this text is **bold**" within the view. That's all.

> and editor.delegate = self can't be allowed in UIViewController, i'm a totally baby bird in ios, really needs help!

You probably need your UIViewController to conform to the [delegate protocol](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html).

As far as I can tell the problems you are describing aren't an actual problem with the library itself. But I can see how you ran into them if you are a "totally baby bird."

**Comment by dev4shane** [comment]
thank you for reply, the text with "/n/t" in it from the server can't be show, finally figure it out

**Comment by cjwirth** [comment]
so a newline and a tab? Yeah, unfortunately those aren't even really visible in HTML. You'll have to convert your text to HTML in order to display it. So, a `<br />` for the newline, etc. 

This project was originally made to have rich text that we could share between iOS, Android, and the Web, which led to the need for HTML
