### ISSUE TITLE
i want to be able to change the font of the text while editing the editor. how do i implement this functionality?

### ISSUE THREAD

**Issue by Abh15h3k** [cjwirth/RichEditorView#172]
right now im just able to set bold, underline, italics. but i also want to be able to change the font (with the option to change the font size as well)

**Comment by friendshipzhang** [comment]
RE.setTextFontSize = function(fontSize){
    document.execCommand("fontSize", false, fontSize);
};
you can insert this code into rich_editor.js  then insert a function in RichEditorView.swift

**Comment by Pawan-Paritem** [comment]
friendshipzhang not working

RE.setTextFontSize = function(fontSize){
document.execCommand("fontSize", false, fontSize);
};
