### ISSUE TITLE
Auto-suggest with @usernames and #hashtags

### ISSUE THREAD

**Issue by cannyboy** [cjwirth/RichEditorView#23]
I'd like the user to be able to enter HTML text (actually just Bold and Italic), and well @usernames and **#hashtags** - with the @usernames and **#hashtags** autosuggested underneath the text-entry.

There are a number of third-party libraries which help with this:
https://github.com/arsonic/AVTagTextView
https://github.com/AdamBCo/ABCAutoCompleteTextView
https://github.com/Mazyod/MJAutoComplete

(all objective-c)

@cjwirth - would you recommend trying to meld RichEditorView with one of these libraries, or is it something that could be added to RichEditorView?

**Comment by cjwirth** [comment]
This is definitely out of scope for this project. Having some kind of autocomplete would require an entirely different view to pop up based on what it typed in.

If I were to go about it, though, I would do it like this... 
Make a JS file that contains all the necessary JS methods for the plugin. Load it into the WebView with `richEditor.runJS(jsFileLoadedAsString)`. 

Make some JS that recognizes when you are in a @username or #hashtag, and calls a custom action when you are. 
Maybe something like this:
```JavaScript
document.addEventListener("selectionchange", function() { 
    var currentUserOrHash = getUserOrHashSelection(); // I'm not really sure how you would get this
    RE.customAction("user-typing-userhash?text=" + currentUserOrHash);
});
```

Then the delegate method `richEditor:handleCustomAction:` would get called with "user-typing-userhash?text=xxxx" as the parameter. You could then parse that incoming data, and do whatever you wanted with the inputted text to display your autocomplete choices.

When the user selects an autocomplete suggestion, you'd probably need to have another JS method that would be called to replace the current @username or #hashtag with whatever they inserted.

**Comment by cjwirth** [comment]
I should probably write some documentation about writing plugins (or the fact that you even can!)

**Comment by SolorzanoJose** [comment]
@cjwirth how do I highlight @user and #hashtag mentions? how do I apply a custom style to those?
