### ISSUE TITLE
The height of Editor does not decrease when I remove newlines

### ISSUE THREAD

**Issue by Abdelilahskali** [cjwirth/RichEditorView#249]
Firstly thank you for this API
I integrated the editor in a uitableviewcell and I increase the height of the cell from the delegate function heightDidChange.
But when I remove the newlines the height always stays the same, the heightDidChange is not called
is there a way to know the new editor height if i delete some text (newlines) to decrease cell height ?

**Comment by BarMalka** [comment]
@Abdelilahskali I can see you closed this issue.
Did you solve this issue? If so, can you share the solution please?

**Comment by IshuRocks** [comment]
@Abdelilahskali  can you please share solution.

**Comment by IshuRocks** [comment]
This solution work for me 

Update code in "**RichEditorView**"

    private func updateHeight() {
        
        runJS("RE.getHtml()") { content in
           
            let attributedString = NSMutableAttributedString(string: content,
                                                             attributes: [
                                                                 .font: UIFont.systemFont(ofSize: 16.0)
                                                             ])

            let stringToMeasure = attributedString.string.replacingOccurrences(of: "<br>", with: "\n")
            let modifiedAttributedString = NSAttributedString(string: stringToMeasure, attributes: [
                .font: UIFont.systemFont(ofSize: 16.0)
            ])

            // Calculate the bounding rect
            let maxWidth: CGFloat = UIScreen.main.bounds.width - 30
            let options: NSStringDrawingOptions = [.usesLineFragmentOrigin, .usesFontLeading]
            let boundingRect = modifiedAttributedString.boundingRect(with: CGSize(width: maxWidth, height: .greatestFiniteMagnitude), options: options, context: nil)

            // Extract the calculated height
            let height = ceil(boundingRect.height)
            self.editorHeight = Int(height)
            print(height)

        }
    }
