### ISSUE TITLE
help for dark mode

### ISSUE THREAD

**Issue by BlackGold-1989** [cjwirth/RichEditorView#253]
How to change RichEditorView background color and text color in darkmode??
There are functions name setEditorBackgroundColor, setEditorFontColor... but does not work..
I need help...

**Comment by BlackGold-1989** [comment]
I found a solution for this...

**Comment by sagarpathak57** [comment]
@BlackGold-1989 what was the solution?

**Comment by BlackGold-1989** [comment]
this is loading web view in pod file, so we set style (css for body). 
@media (preferss-color-scheme: light), @media (preferss-color-scheme: dark) which is same when we set theme in web development.
That's all.
