### ISSUE TITLE
View doesn't scroll if you keep typing out of bounds

### ISSUE THREAD

**Issue by leolobato** [cjwirth/RichEditorView#3]
When you're typing into RichEditorView, if you add a new line which is out of the view bounds, it will not scroll automatically to the cursor.

**Comment by cjwirth** [comment]
This is a good point. In our own application, we enlarge the view when the internal height changes, but I can see how that wouldn't work for all cases. 

Let me see if I can put something together.

**Comment by cjwirth** [comment]
I can't say for certain right now, but this might end up being some sort of plugin or add-on. I had to get this working for when the cursor went below the keyboard, and there was a lot of extra code involved. 

The scope was larger than just the one view, though, so maybe I can do it with a reasonable amount of code.

**Comment by leolobato** [comment]
I ended up implementing on a project which does something similar (UIWebView with contentEditable) by listening to changes on the window, fetching the cursor position using javascript and setting the UIScrollView contentOffset.

**Comment by cjwirth** [comment]
Ah, that might work. In my own project, I ended up copypasting and changing the JS in [this StackOverflow question](http://stackoverflow.com/questions/6846230/coordinates-of-selected-text-in-browser-page) to get the location of the cursor within the UIWebView. I guess using that, and then updating the `contentOffset` wouldn't add as much code as I thought.

**Comment by leolobato** [comment]
Yep. That is similar to the one I ended up using, but I've stripped the ```x``` response so it would only respond with the vertical position of the cursor (which is what matters to us).

**Comment by idealx** [comment]
Add a pull request to fix this issue.
https://github.com/cjwirth/RichEditorView/pull/5

**Comment by cjwirth** [comment]
I've tried fixing this a few times, but I keep running into the same problem.
Once the cursor gets past the length of the view, the position of where it thinks the cursor is ends up wrong.

![untitled](https://cloud.githubusercontent.com/assets/1579644/11237397/fe90317a-8e22-11e5-8da3-8d7fa549f220.gif)

The red line is where the REV thinks the cursor is. Each newline, before typing a character, the cursor gets reset to be the position of where the bottom originally was. This is coming from JS, and I'm not sure how to get around that.

**Comment by cjwirth** [comment]
I pushed what I had (including the debug cursor) up to the [fix/scroll-with-cursor](https://github.com/cjwirth/RichEditorView/tree/fix/scroll-with-cursor) branch, if anyone wants to take a look. If this kink can get ironed out, I think this issue can be resolved.

**Comment by gilgold** [comment]
Hey, any update on this? Really want to use this component but the scroll bug is a big issue for me :/

**Comment by cjwirth** [comment]
Unfortunately, I'm still stuck at the place I was at in November. 
In truth, I only come back to it every few weeks, and I end up running into the same problem. I don't really know what's causing it, otherwise I'd fix it...

**Comment by KunHub** [comment]
hey, is there some solution for this problem? I am so glad to find RichEditorView, but there is such a bug that I can't use it, so sad

**Comment by cjwirth** [comment]
Still there unfortunately. Sorry I haven't been very active to fix this one -- I know it's really something that should be fixed, but my use case just made the view bigger :sweat_smile:

Ech time I try to fix it, I run into the problem above, and I don't know why it does that. If anyone knows or has any ideas, I'd love to know.

**Comment by cjwirth** [comment]
@SteenJobs Has made a pull request that mostly solves the issue: https://github.com/cjwirth/RichEditorView/pull/34

It might be similar to my [fix/scroll-with-cursor](https://github.com/cjwirth/RichEditorView/tree/fix/scroll-with-cursor) branch, so if anyone wants to take a look. 

They're both a little buggy, but at least there's a starting point.

If people think this is at least enough to solve their problem, I can merge it into master, and we can open other issues for the bugs.

Let me know what you guys think! :smile:

**Comment by KKKiller** [comment]
i have test it,it is almost fix the bug althought it is not such perfect. you can just merge it into master,i think ,and appreciate for your errfort!

**Comment by SteenJobs** [comment]
Make sure to test the most recent commits, and let me know what other bugs you find.

**Comment by KKKiller** [comment]
i got some bugs when i use it!
if i just type return without any word,it will not offset
and if i insert  a big image,it will not offset as i want too
and if i type crazly and fast,the offset  will not  response as soon as it. (it is just ok with that)

**Comment by cjwirth** [comment]
> if i insert a big image,it will not offset as i want too

Try this one again after merging both https://github.com/cjwirth/RichEditorView/pull/33 and https://github.com/cjwirth/RichEditorView/pull/34 . There is a different bug when it comes to inserting pictures. It might be related.
