### ISSUE TITLE
How I can change the UIView container size?

### ISSUE THREAD

**Issue by marcextv** [cjwirth/RichEditorView#30]
Hi, I' trying to change the container size, because the HTML is bigger that it, putting up on antohers views. Can you help me?

Thanks

**Comment by cjwirth** [comment]
> putting up on antohers views

I'm not sure what you mean with this part.

You should to be able to just make the RichEditorView bigger like any other view if you need to.

**Comment by marcextv** [comment]
Sorry

I've found the solution


Hehe

**Comment by cjwirth** [comment]
Great! :+1:
