### ISSUE TITLE
memory increasing when insert image from album

### ISSUE THREAD

**Issue by KKKiller** [cjwirth/RichEditorView#36]
when i inset  images from album,the memory will be increasing, what can i do to slove the problem?

**Comment by cjwirth** [comment]
Does the memory decrease after deleting the image, or does it stay increased? Also, does the memory decrease again after the RichEditorView is removed?

**Comment by KKKiller** [comment]
it was still keep high memory when i delete the image,and when i go to album before i choosed a picture ,the memory is aleary 200M,what is the problem? and thanks a lot for your help!!!

**Comment by cjwirth** [comment]
So the memory is low when you have the editor open, then it gets high when you open the album, then you choose the picture, and after that even if you delete the picture it stays high? 

How are you opening the album?

**Comment by KKKiller** [comment]
yes ,it is perform as you said.  i get the image by way of the follow code. is there is problem?

`- (void)getImageFromAlbum {
    UIImagePickerController *controller = [[UIImagePickerController alloc] init];
    controller.delegate = self;
    controller.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
    [self presentViewController:controller animated:YES completion:NULL];
}

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    UIImage *image = info[UIImagePickerControllerOriginalImage];
    CGSize size = image.size;
    if (size.width > self.view.frame.size.width - 2) {
        size.height = ((self.view.frame.size.width - 2)/size.width) * size.height;
        size.width = self.view.frame.size.width - 2;
    }
    [self dismissViewControllerAnimated:YES completion:NULL];
    
    NSString *imgPath = [self convertImagetoUrlPath:image];
    NSString *width = [NSString stringWithFormat:@"%f",size.width];
    NSString *height = [NSString stringWithFormat:@"%f",size.height];
    [self.keyboardManager.toolbar.editor insertImage:imgPath alt:@"" width:width height:height];
    
}`

**Comment by cjwirth** [comment]
You know, when you open the `UIImagePickerController`, I'm pretty sure you are loading a lot of image assets into memory. This even happens with a very small sample application with nothing in it except a button that opens the albums:

![screen shot 2016-03-26 at 12 28 37 am](https://cloud.githubusercontent.com/assets/1579644/14047217/e0580fa8-f2e9-11e5-9b56-a566fc74f244.png)

1. Opened up the `UIImagePickerController` --> memory basically doubled
2. Opened up an album (only 5 images -- the defaults in the simulator)
3. Canceled out of the picker (dismissed it)

Lots of still memory is still being used. 

So, this isn't really an issue with the RichEditorView itself, it's the default behavior of `UIImagePickerController`. I don't think it should cause any problems, and so I am going to close this issue :smile:
