### ISSUE TITLE
Actually This is not any issue i am just asking my requirment....

### ISSUE THREAD

**Issue by sreeji44** [cjwirth/RichEditorView#37]
Here you added somany toolbar.. i just want just 4 needed.. first one is text adding.. second orderedList,3rd bullets, images... how can i add this..

**Comment by cjwirth** [comment]
I'm guessing you are just using the default `RichEditorToolbar` that comes included with the editor.

The `RichEditorToolbar` has an `options` property that takes an array of items of type `RichEditorOption`. Now, `RichEditorOption` is a protocol, so you can pass in whatever you need, and each button can perform whatever you want it to (including the `RichEditorOptionItem`, a struct that takes a title, optional image, and a tap handler)

If you just need some of the default options (you said ordered lists and bullets), then you might be able to pass in some of the values of `RichEditorOptions`, an enum that has some default options available to you. In particular, you might want do do something like:

~~~swift
toolbar.options = [RichEditorOptions.OrderedList, RichEditorOptions.UnorderedList]
~~~

**Comment by sreeji44** [comment]
thankx for the reply.. Is their any way to change number ordered list to checkbox list... we can edit the number list to checklist.. ?

**Comment by cjwirth** [comment]
Yeah no problem!

As far as I know, there's no way to change `<ul>` or `<ol>` to a list of checkboxes without putting a checkbox element inside each `<li>` tag.. If you wanted to add that kind of functionality, you'd have to write some JS in order to handle it the way you wanted. 😥

**Comment by sreeji44** [comment]
ok sir...  i just want that format...
![screen shot 2016-02-12 at 2 06 35 pm](https://cloud.githubusercontent.com/assets/16497980/14071796/aff78f02-f4d6-11e5-957f-f7beb9df91d5.png)
![screen shot 2016-02-12 at 2 06 12 pm](https://cloud.githubusercontent.com/assets/16497980/14071799/b1acce5c-f4d6-11e5-8cda-4b38741d5d8a.png)
![screen shot 2016-02-12 at 2 06 00 pm](https://cloud.githubusercontent.com/assets/16497980/14071800/b2f8577c-f4d6-11e5-9299-e46f9727adfd.png)
![screen shot 2016-02-12 at 2 06 00 pm](https://cloud.githubusercontent.com/assets/16497980/14071802/b4e7d7d8-f4d6-11e5-844a-f19b3d355665.png)


My Requiremrnt is this....

**Comment by cjwirth** [comment]
Sorry, but that's beyond the scope of what this library provides. I would suggest finding out how to do it in HTML and JS, and loading the JS into the RichEditorView, and triggering the actions that you need to happen in there. This library just wraps around a UIWebView, so anything you can do in there, you can do in RichEditorView. You will just have to figure out how to do it.

**Comment by sreeji44** [comment]
thanks for the reply... :) :+1:

**Comment by sreeji44** [comment]
@cjwirth Need to know something, on return key tap the focus moves to the next line. where have written that code ???

**Comment by cjwirth** [comment]
I haven't written anything to make the return key go to the next line? I think that's just how the web view handles return presses. Unless something weird is going on?

**Comment by sreeji44** [comment]
@cjwirth no actually i am just asking my doubt. is this possible in uiscrollview?.

**Comment by cjwirth** [comment]
Do you mean you want something like this https://github.com/cjwirth/RichEditorView/pull/34 ?
@jesiegel1 Is working on getting it to work. It's really close to being done, but has one more bug we gotta fix.

**Comment by sreeji44** [comment]
@cjwirth  ya as same as this issue.
