### ISSUE TITLE
version < 4.4 can not delete image tag

### ISSUE THREAD

**Issue by chenqingfeid** [cjwirth/RichEditorView#39]

**Comment by cjwirth** [comment]
Hey! Thanks for your interest :+1: 

Sorry, do you think you could clarify what you mean? In particular, I'm not sure what you mean by version < 4.4

**Comment by cjwirth** [comment]
ping?

**Comment by cjwirth** [comment]
ping?

**Comment by cjwirth** [comment]
Closing because of lack of information.
