### ISSUE TITLE
How to define a 'Done' button at toolbar on the right

### ISSUE THREAD

**Issue by codwam** [cjwirth/RichEditorView#40]
Just like iqkeyboardmanager..

**Comment by cjwirth** [comment]
What is your setup like? What are you using for the toolbar? 

If you're using the RichEditorToolbar, there's really no good way to do it with the current setup. It just takes all the input options and lays them out left to right, scrolling if it's necessary.

**Comment by codwam** [comment]
ok, so could I insert a local image to the editor directtly?

**Comment by cjwirth** [comment]
I'm not sure what you mean. The Done button isn't being displayed in the editor -- it's being displayed in the toolbar. 

You could probably get it to work -- but the buttons would still be scrolling until the end of the toolbar, not to where your Done button is. You would probably have to add a dummy item at the end to make up for it.
