### ISSUE TITLE
Add option to change toolbar tintColor

### ISSUE THREAD

**Issue by KKKiller** [cjwirth/RichEditorView#41]
i want to use my picture to replace the picture at your project. such as bold,undo. i delete your picture and insert my own picture. it does not work. why?

**Comment by KKKiller** [comment]
the picture is worked,but the tintColor was changed to blueColor,how could i close the fuction and to show my original picture at the toolbar

**Comment by cjwirth** [comment]
How did you get the picture to work? The right way to do it is to create something that conforms to the `RichEditorOption` protocol (you could use the `RichEditorOptionItem` struct easy enough). 

About the tintColor --> That's not something that I had really thought of. That's something that I could add to it.

**Comment by DominikButz** [comment]
One way is to override RichEditor toolbar and extend RichBarButtonItem by two additional convenience init functions. See below.  
However, you need to change the updateToolbar() function in RichEditorToolbar.swift to public...  

if anyone finds a simpler way to achieve this (without messing up cjwirth's brilliant code) please let me know. 

public class DYEditorToolbar: RichEditorToolbar {
    
    override public func updateToolbar() {
        print("update toolbar")
        var buttons = [UIBarButtonItem]()
        
        for option in options {
            
            
            if let image = option.image() {
                
                let button = RichBarButtonItem(image: image, tintColor: UIColor.[your colour], showsActiveState:false ) { [weak self] in  option.action(self) }
                buttons.append(button)
            } else {
                let title = option.title()
                let button = RichBarButtonItem(title: title, tintColor: UIColor.[yourcolour], showsActiveState: false) { [weak self] in option.action(self) }
                buttons.append(button)
            }
            
        }
        toolbar.items = buttons
        
        let defaultIconWidth: CGFloat = 22
        let barButtonItemMargin: CGFloat = 11
        let width: CGFloat = buttons.reduce(0) {sofar, new in
            if let view = new.valueForKey("view") as? UIView {
                return sofar + view.frame.size.width + barButtonItemMargin
            } else {
                return sofar + (defaultIconWidth + barButtonItemMargin)
            }
        }
        
        if width < self.frame.size.width {
            toolbar.frame.size.width = self.frame.size.width
        } else {
            toolbar.frame.size.width = width
        }
        toolbar.frame.size.height = 44
        toolbarScroll.contentSize.width = width
    }
    
}

extension RichBarButtonItem {
    

    convenience init(image: UIImage? = nil, tintColor:UIColor, showsActiveState:Bool, handler: (Void -> Void)? = nil) {
        
        self.init(image: image, style: UIBarButtonItemStyle.Plain, target: nil, action: nil)
        self.tintColor = tintColor
      
        target = self
        action = #selector(self.buttonWasTapped)
        actionHandler = handler
        
    }
    
    
    convenience init(title: String = "", tintColor:UIColor, showsActiveState:Bool, handler: (Void -> Void)? = nil) {
        self.init(title: title, style: .Plain, target: nil, action: nil)
        target = self
        action = #selector(self.buttonWasTapped)
        actionHandler = handler
        self.tintColor = tintColor
     
        
    }
    
    
}

**Comment by cjwirth** [comment]
Yeah I don't think it would be that hard to add. I kind of added the toolbar just as a default in case people wanted to use it, I didn't really expect people to use it -- I was thinking they'd want/need their own custom UI. 

> if anyone finds a simpler way to achieve this (without messing up cjwirth's brilliant code) please let me know.

haha 😅 I don't know, there are certainly places I would like to change, but I don't want to force people into a major upgrade just because some of my stylistic opinions have changed.

But hey, if you want to go in and add a tint color to the toolbar or each individual item, you can send a pull request if you want to. I think it would make more sense to have it on the toolbar, personally.

**Comment by DominikButz** [comment]
I have created a fork and a new branch called toolbarEnhancements.  I'm quite new to iOS programming, I had forgotten that UIToolbar has a  tintColor property that changes the tintcolor of its UIBarButtonItems.
So I have simply added a function to  RichEditorToolbar. 

https://github.com/DominikButz/RichEditorView/tree/toolbarEnhancements

This way it's easier to change the tint colour of all bar button items:

  lazy var toolbar: RichEditorToolbar = {
        let toolbar = RichEditorToolbar(frame: CGRect(x: 0, y: 0, width: self.view.bounds.width, height: 44))
        toolbar.options = RichEditorOptions.all()
        
     **   toolbar.setCustomTintColor(UIColor.greenColor())**
        
        return toolbar
    }()

maybe I'll add some more changes later.

**Comment by cjwirth** [comment]
OK, so as it turns out, since iOS 7, every view has a `tintColor` property. The RichEditorToolbar's tintColor can be changed just like that.

Although, I did add a wrapper property so you can change the `barTintColor` so you don't have to use the default gray if you don't want to.

Check it out on the `develop` branch!
