### ISSUE TITLE
How can I set text color to black?default is lightgray.

### ISSUE THREAD

**Issue by shiwwgis** [cjwirth/RichEditorView#43]
I seems there is no method to set default text color,settextcolor  maybe is useful  to selected text only?

**Comment by cjwirth** [comment]
I'm pretty sure you're right that `setTextColor` will only change the current selection. That bit is handled by the `contentEditable` API and not the library, so I don't think is a way to change that behavior.

What we are doing is just loading another CSS file. For instance what we are doing is

~~~ css
@font-face {
    font-family: 'MyFont';
    src: url('custom-font.ttf');
    font-weight: normal;
    font-style: normal;
}

#editor {
    font-family: 'MyFont';
    color: #666;
}
~~~

And then loading the CSS file with

~~~ swift
/// Reads a file from the application's bundle, and returns its contents as a string
/// Returns nil if there was some error
func readFile(name name: String, type: String) -> String? {
    if let filePath = NSBundle(forClass: ClassInMyProject.self).pathForResource(name, ofType: type) {
        do {
            let file = try NSString(contentsOfFile: filePath, encoding: NSUTF8StringEncoding) as String
            return file
        } catch let error {
            print("Error loading \(name).\(type): \(error)")
        }
    }
    return nil
}

/// Creates a JS string that can be run in the WebView to apply the passed in CSS to it
func addCSSString(style: String) -> String {
    let css = self.cleanStringForJS(style)
    let js = "var css = document.createElement('style'); css.type = 'text/css'; css.innerHTML = '\(css)'; document.body.appendChild(css);"
    return js
}

/// Loads the custom CSS, swaps out the fonts with those in the bundle, and applies it to the editor
if let customCSS = readFile("style", "css") {
    var newCSS = customCSS
    let bundle = NSBundle.mainBundle()
    
    /// Replace the font with the actual location of the font inside our bundle
    if let fontLocation = bundle.pathForResource("custom-font", ofType: "ttf"),
        newCSS = newCSS.stringByReplacingOccurrencesOfString("custom-font", withString: fontLocation)
    }
    let js = addCSSString(newCSS)
    editor.runJS(js)
}
~~~

This is how we are loading CSS and we do the same thing for loading custom JS files too. 
You should be able to customize the defaults however you want with this.

**Comment by cjwirth** [comment]
Did this work for you, or maybe you need something else?

**Comment by cjwirth** [comment]
Since there's been no response, I'm going to assume it solved your problem 😄 

If you still need more help, feel free to respond or reopen the issue!

**Comment by GianniCarlo** [comment]
Hi @cjwirth the proposed solution only works on `viewDidAppear` if it's done in `viewDidLoad` it seems like the internal webview isn't ready yet and it won't have any effect, any recommendations?

**Comment by GianniCarlo** [comment]
Ok got it, if it's done inside the delegate function `richEditorDidLoad(_ editor: RichEditorView)` it works. Thanks @cjwirth
