### ISSUE TITLE
Setting background transparent not working

### ISSUE THREAD

**Issue by Techprimate** [cjwirth/RichEditorView#46]
I tried to set the background to a clear color using this code:

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        headerLabel.text = data.header
        contentTextView.editingEnabled = false
        contentTextView.delegate = self
        contentTextView.setHTML(data.content)
    }

func richEditorDidLoad(editor: RichEditorView) {
        contentTextView.backgroundColor = UIColor.clearColor()
        contentTextView.webView.backgroundColor = UIColor.clearColor()
        contentTextView.webView.opaque = false
        contentTextView.inputAccessoryView?.backgroundColor = UIColor.clearColor()
    }
```

But after appearing the view looks like this:
![simulator screen shot 09 may 2016 17 31 29](https://cloud.githubusercontent.com/assets/4140457/15118344/1cd00d60-160c-11e6-961c-f0f3e5c34332.png)

If i rotate the view and rotate it back the view looks correct like this:
![simulator screen shot 09 may 2016 17 31 33](https://cloud.githubusercontent.com/assets/4140457/15118348/20422e2e-160c-11e6-9148-03c35a967dc1.png)

Seems like it is some kind of redraw error! Any combination of `setNeedsToDisplay()` and `layoutIfNeeded()` did not work.

The HTML code: 
`<h1 style="color: rgb(256, 0, 0);"><font size="3"><span style="font-weight: normal; -webkit-text-size-adjust: 100%;">Simply press the</span><span style="-webkit-text-size-adjust: 100%;"> + </span><span style="font-weight: normal; -webkit-text-size-adjust: 100%;">button in the main view and a new recipe base on the default template will be created!</span></font></h1>`

Any idea why webview is acting like this?

**Comment by Techprimate** [comment]
![simulator screen shot 09 may 2016 17 36 03](https://cloud.githubusercontent.com/assets/4140457/15118456/8579ea5c-160c-11e6-8c2e-3ff8bf5e5671.png)

Here you can see the webview has the correct size.

**Comment by Techprimate** [comment]
Suddenly it hit me: 
I tried a different approach and this one works:

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        headerLabel.text = data.header
        contentTextView.editingEnabled = false
        contentTextView.backgroundColor = UIColor.clearColor()
        contentTextView.webView.backgroundColor = UIColor.clearColor()
        contentTextView.webView.opaque = false
        contentTextView.inputAccessoryView?.backgroundColor = UIColor.clearColor()
        
        contentTextView.setHTML(data.content)
    }
```

You might want to include this in the README, that if you want to customize the RichEditorView you need to do it before setting the HTML

**Comment by cjwirth** [comment]
Aaahh, yeah I guess I could put something like that in the README, sorry about that.
This is basically just a wrapper around a UIWebView with some custom JS being loaded -- so `richEditorDidLoad` doesn't get called after being instantiated, rather after all the necessary HTML and JS has been loaded.

Glad you got it working though 👍
