### ISSUE TITLE
editor view's web view doesn't retrieve image file from Documents folder

### ISSUE THREAD

**Issue by DominikButz** [cjwirth/RichEditorView#47]
Hi,
this might not be directly related to this framework, but maybe someone can give me a hint to the right direction to take for solving this problem.

When I try to insert an image like so:
toolbar.editor!.insertImage(fileURL.absoluteString, alt: "new image")

all works fine. 

The image data is written to a file in the documents folder and then the refreshed html contains the image tag with the image path. 

However, after I stop the simulator and restart it, the image can't be loaded into the html of the editor's web view properly. 

See the screenshots below. The image tag in the html looks like this
\<img src="file:///Users/Dominik/Library/Developer/CoreSimulator/Devices/BC19750C-FE45-4C7A-853E-1933DE0B5515/data/Containers/Data/Application/6F3EFBA9-E1CA-45F7-9567-D5E653972DB6/Documents/3E9BCE98-033D-4754-9125-683F704E2CEA.jpg" alt="image">

I have checked in the finder that the file is there... it has been saved indeed. doesn't matter if I convert the ui image to jpg or to png. 
The weird thing is that when creating the the file, the web view has to update as well and retrieve the file from the documents folder. Otherwise it wouldn't show....  the html string is properly retrieved from core data, otherwise there would not be any text with html text attributes. 

![screen shot 2016-05-13 at 17 10 06](https://cloud.githubusercontent.com/assets/5699871/15243407/fe9bd408-192d-11e6-8963-c946b5ed488c.png)

![screen shot 2016-05-13 at 17 08 37](https://cloud.githubusercontent.com/assets/5699871/15243445/3d78b376-192e-11e6-8027-2e5d35ddf1a2.png)

**Comment by DominikButz** [comment]
Thanks for looking into this!  The code that saves the image to the Documents folder of the app is very similar to yours (see below). I also tried using safari in the simulator to save some random image to the simulator camera roll rather than using one of the default images.  The result is the same...    
In the logic of this app however, the user cannot just insert an image by adding a web URL. It all works through the camera or the image library. 

After dismissing the edit view, the image and reopening the same item ( a note object in this case), the image appears as part of the Html. but I guess it is kept in cache so the simulator does not actually reload it from the documents folder...  
When I stop the simulator and rebuild however, the web view in the editor apparently can't reload the image...  

text information in the html-string can be retrieved without any problem though - it is just the image that is missing. 




    func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) {

            if let pickedImage = info[UIImagePickerControllerOriginalImage] as? UIImage {
                
                if let imageData = pickedImage.resizeImage(200.0 , maxWidth:300.0, compression:0.7) {
                    
                     let filename = NSUUID().UUIDString + ".jpg"
                    
                    let path = getDocumentsURL()
                    
                    let fileURL = path.URLByAppendingPathComponent(filename)

                    print("file url: \(fileURL)")
                   
                    do {
                        try imageData.writeToURL(fileURL, options: NSDataWritingOptions.DataWritingAtomic)
                    }
                    catch let error as NSError  {
                        
                        print(error)
                    }
   
                    self.keyboardToolbar.editor?.insertImage(fileURL.absoluteString, alt: "new image")

                    dismissViewControllerAnimated(true, completion: {

                        print("file url abs string \(fileURL.absoluteString)")
                    })
                    
                }
    
            
        }
        
            else {
                dismissViewControllerAnimated(true, completion: nil)
        }
     
        
    }



    func getDocumentsURL() -> NSURL {
        let documentsURL = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
        return documentsURL
    }

**Comment by cjwirth** [comment]
Ah, I see. You're actually saving the local image URL in the HTML, and then displaying it again the next time with the same HTML.

I played around with it again today. It seems like the Documents directory URL is changing each time you launch the app. For example, for one run, I got 
```
file:/// ... /Application/6D820E65-30F6-480A-90FE-C31B0CDB6F65/Documents/pasta.jpg
```

But then the next time I got 
```
file:/// ... /Application/6399E27A-E729-46D6-A523-45FD2D65CFBA/Documents/pasta.jpg
```

So it worked for my sample code, because I am always generating the documents directory code before inserting it into the web view.

For you, it's a little bit more difficult. I might suggest, when you save the HTML, you take the documents directory, and change it to some token, like `[DOCUMENTS_DIRECTORY]/pasta.jpg` . Then, when you load the content the next time, you pre-process the HTML, changing `[DOCUMENTS_DIRECTORY]` with whatever the real new documents directory is.

How does that sound, does that fit your situation?

**Comment by cjwirth** [comment]
I think I'm going to close this issue, because I don't think it's really a problem with the editor itself. I don't think local URLs like that were supported in the first place (or else why would they change the directory? lol)

If you think differentl or something, feel free to reopen the issue 👍

**Comment by DominikButz** [comment]
Thank you for figuring this out!  I have opened the sub folder in the core simulator path and indeed the folder name changes every time I do a new build.   
This is actually an issue that only occurs in the simulator. I have just tested my app on a real device for the first time. When I add an image to a note, save it and then simply remove the app from memory and re-start it, the image is displayed as expected.  Thanks anyway and yes, you can close they issue!

**Comment by NancyZY** [comment]
@DominikButz  Can you get the resizeImage()  method  in there ?  I try to pick image from Photo Library, and then set image to "toolbar.editor", there I found you have worded that . So I copied your code ,then showed error in  resizeImage()  method . Need your help, Thx

**Comment by cjwirth** [comment]
You won't be able to just copy/paste it, but I'm pretty sure he's using an extension on UIImage that has a `resizeImage` method that looks something like [what is in the SO answer](http://stackoverflow.com/a/29137723)

**Comment by DominikButz** [comment]
yes, that is correct, I used an extension to UIImage. there are several ways of resizing images. you can find a lot of solutions on numerous sites.

here is the one I used:

public extension UIImage {
    
    public func resizeImage(maxHeight:CGFloat, maxWidth:CGFloat, compression:CGFloat)->NSData? {
        
        var actualHeight = self.size.height
        var actualWidth = self.size.width
        var imgRatio = actualWidth/actualHeight
        let maxRatio = maxWidth/maxHeight

        if actualHeight > maxHeight || actualWidth > maxWidth
        {
            if imgRatio < maxRatio
            {
                //adjust width according to maxHeight
                imgRatio = maxHeight / actualHeight
                actualWidth = imgRatio * actualWidth
                actualHeight = maxHeight
            }
            else if(imgRatio > maxRatio)
            {
                //adjust height according to maxWidth
                imgRatio = maxWidth / actualWidth;
                actualHeight = imgRatio * actualHeight;
                actualWidth = maxWidth;
            }
            else
            {
                actualHeight = maxHeight;
                actualWidth = maxWidth;
            }
        }

        let rect = CGRectMake(0, 0, actualWidth, actualHeight)
        UIGraphicsBeginImageContext(rect.size)
        self.drawInRect(rect)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        let imageData = UIImageJPEGRepresentation(image, compression)
        UIGraphicsEndImageContext()
        
        return imageData! as NSData
        
    }
    
    
}

**Comment by NancyZY** [comment]
So kind of you, I just wonder why I insert image does not work, I made the class  achieve UIImagePickerControllerDelegate , there in
`func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) `  like the DominikButz's code , then there no image insert, I try to print some information  , the console has no hint. I cannot find the result

**Comment by cjwirth** [comment]
Did you set you class to be the image picker's delegate? Is the delegate method actually being called?

**Comment by DominikButz** [comment]
yes, you need to create an instance variable like   let imagePicker = UIImagePickerController() first and in viewDidLoad :    imagePicker.delegate  = self
use print(...) and check in the console if the function  didFinishPickingMediaWithInfo   is called.
