### ISSUE TITLE
I can't textColor by using `setTextColor`

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#55]
I have called **RichEditorView.setTextColor** on `richEditorDidLoad`.

When it call I have passed `redColor`, but text color is still `grayColor`?
How can I change it?

And can you add method to set `font family`, `line-height` for customized style in your `style.css`, ...?
It is very difficult to customize css.

**Comment by cjwirth** [comment]
What text color are you trying to change? `setTextColor()` changes the color of wherever the cursor is. This means that it will do one of 2 things:

1. If some text is selected -> It will turn the selected text's color
2. No text is selected -> It will change the color of the text input after where the cursor is.

What it does _not_ do is change the default color of all the text of the editor. That needs to be done by CSS. 

You're not the first one to have this problem, so maybe I should make the CSS customization easier, or actually have the necessary functions built in.

**Comment by GianniCarlo** [comment]
+1
