### ISSUE TITLE
run the RichEditorViewSample ,but not working to the simulator

### ISSUE THREAD

**Issue by Gavinhhy** [cjwirth/RichEditorView#57]
1.run the RichEditorViewSample ,but not working to the simulator
2.I writed the same codes as your RichEditorViewSample in swift ,but i got a error where focus on "editorView.delegate = self "
can you tell me the reasons? thanks

**Comment by cjwirth** [comment]
Hi! 😃  Sure, I can try to help you out!

Can you tell me:

- What version of Xcode you are using
- What branch you are using when running
- What you mean by "not working" --> does it not build? If so, what's the error?

**Comment by Gavinhhy** [comment]
Thank you !
1.my xcode version is 7.3
2.I am running the branch of swift 
3.when i press "cmd + r"，it build succeeded,but the simulator do not start and launch the project
4.when i running my new demo which same to yours , i get a error ,it shows "Thread 1:EXC_BAD_ACCESS(code=2,address=0x1110a1170)"  and focus on my code "editorView.delegate = self"
sorry for my swift and english ~

**Comment by Gavinhhy** [comment]
![2016-05-26 15 31 41](https://cloud.githubusercontent.com/assets/9283541/15567101/fb4d6068-2356-11e6-9dec-9c59bbd54342.png)
this is my screen shot

**Comment by cjwirth** [comment]
Well that is really weird, it's working for me...

So, you're running your own version of the sample -- if the `editorView` is an `@IBOutlet`, are you sure that it's connected in the storyboard?

**Comment by Gavinhhy** [comment]
I am sure.
it connected  in a UIView of my storyboard which named editorView and type is UIView ,than I changed the type to RichEditorView manually。am i right?

**Comment by cjwirth** [comment]
Yeah it sounds like you hooked it up right... I'm not really sure why it would be crashing on you... everytime, yeah? 

Does it say anything in the debug console when it crashes? What about when you do `po self` or `po editorView` or `bt` ?

**Comment by Gavinhhy** [comment]
Thank you ,man.
Now,i changed my way ,i iinstantiated RichEditorView by code and without outlet .i build it succee,i can typing what i want but insert image.when i touch the icon of insert image , then nothing happen.

**Comment by cjwirth** [comment]
Have you set up the delegate? Is the delegate method being called?

**Comment by cjwirth** [comment]
by the way, the button presses will be coming through the toolbar's delegate, not the editor view's delegate.

**Comment by Gavinhhy** [comment]
I got it  and did it ,but the function "insertImage" only accept url parameter？can i insert image from my iphone?

**Comment by cjwirth** [comment]
Ah, there's actually [an open bug](https://github.com/cjwirth/RichEditorView/issues/47) for things like that. 

The RichEditorView is actually just a small wrapper around a UIWebView, so what we end up doing is making a `<img src="SOME_URL">` tag -- that's why it takes a URL.

**Comment by Gavinhhy** [comment]
ok , I see .thank you anyway. Your project is awesome!

**Comment by cjwirth** [comment]
Yeah, sorry about that! 

If you want to go and make it work how you want, I'm open to pull requests! 😉
