### ISSUE TITLE
Have you prepared similar editor for Windows 10 UWP apps?

### ISSUE THREAD

**Issue by kinju4374** [cjwirth/RichEditorView#60]
Hi, both iOS and Android APIs are really very much helpful but is there same API for Windows Developers also?

If not, are you planning for it?

**Comment by cjwirth** [comment]
Hey kinju4374! I'm glad that you're enjoying it 😃 👍 

Unfortunately, I don't have any plans to do anything for Windows. I've never done any development for Windows, but I'm sure you could do something very similar to this if you wanted to!

If you do find anything, or you end up making something, let me know and I'll add something to the README 🎸
