### ISSUE TITLE
Not working with COCOAPODS 1.0.0

### ISSUE THREAD

**Issue by whitewizard007** [cjwirth/RichEditorView#62]
After i upgrade my Cocoapods to 1.0.0, i cannot type anything on RichEditorView and all icon on toolbar are gone.

>> Before upgrade
<img width="321" alt="screen shot 2559-05-31 at 11 38 14" src="https://cloud.githubusercontent.com/assets/13043501/15663395/cd3c6968-2724-11e6-9883-a94267f71b65.png">

>> After upgrade Cocoapods
<img width="322" alt="screen shot 2559-05-31 at 11 33 43" src="https://cloud.githubusercontent.com/assets/13043501/15663393/c95cd3f0-2724-11e6-81f9-a08a1abbe551.png">

Please help me to investigate and solve this problem.

**Comment by cjwirth** [comment]
Have you tried the sample project? What does your Podfile look like?

**Comment by cjwirth** [comment]
I just tried this with the sample program. I had to update the Podfile to work with CocoaPods 1.0.0, but it worked just fine...

**Comment by whitewizard007** [comment]
Yes. I tried on the same project. This is my Podfile.

`[Nutnapuns-MacBook-Pro:GO10 nutnapunakk$ cat Podfile
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GO10' do
	pod 'Google/SignIn'
	pod 'CarbonKit', '~>2.1'
	pod "RichEditorView"
	pod 'Toucan', '~> 0.5'
end

target 'GO10Tests' do

end

target 'GO10UITests' do

end
`

**Comment by cjwirth** [comment]
Hmm... I just tried using your Podfile on a new project and it worked just fine 😕 

Have you tried any / all of these?

- Deleting Derived Data
- Deleting the Build Directory (if it's not in the Derived Data)
- Deleting the `Pods/` directory and re-installing
- Clearing CocoaPods cache `pod cache clean --all`
- etc

I was upgrading to Xcode 7.3.1 and CocoaPods yesterday, and there was a whole lot of old data that I had to delete to get it to even build my project.

**Comment by whitewizard007** [comment]
Wow. It's work. I just delete Derived Data at "~/Library/Developer/Xcode/DerivedData" as your suggestion. Thank you so much for your help.

**Comment by cjwirth** [comment]
\\(^o^)/

No problem, glad it's working for you :)
