### ISSUE TITLE
Strange format style.

### ISSUE THREAD

**Issue by Ying1986** [cjwirth/RichEditorView#65]
This is the html text from this library (orderlist).
`<div>B</div><div><ul><li>1</li><li>2</li></ul><div>C</div></div><div><ul><li><span style="font-size: 12pt; -webkit-text-size-adjust: 100%;">11</span><br></li><li><span style="font-size: 12pt; -webkit-text-size-adjust: 100%;">22</span></li></ul></div>`

<div>B</div><div><ul><li>1</li><li>2</li></ul><div>C</div></div><div><ul><li><span style="font-size: 12pt; -webkit-text-size-adjust: 100%;">11</span><br></li><li><span style="font-size: 12pt; -webkit-text-size-adjust: 100%;">22</span></li></ul></div>

Test on https://html-online.com/editor/   (I find the same issue on my iPhone)
![image](https://cloud.githubusercontent.com/assets/6648212/15773885/2b6e6248-2982-11e6-9df8-f3dc808a0f0f.png)

Why added new **span** style to 2nd list block?

**Comment by cjwirth** [comment]
I don't know, really. I'm not doing anything purposely to change any of the styling. Have you applied any custom CSS? 

I did a little bit of googling and found [these](http://stackoverflow.com/questions/6210788/how-to-avoid-ios-automatic-font-size-adjustment) [pages](http://blog.55minutes.com/2012/04/iphone-text-resizing/) and it seems like iOS wants to resize text sometimes? I'm guessing it's some quirk with UIWebVIew, the CSS, and editing text in contentEditable divs...

**Comment by cjwirth** [comment]
ping?

**Comment by cjwirth** [comment]
Are there any updates with this I should know about?

**Comment by cjwirth** [comment]
Closing because this is super old with no response.
