### ISSUE TITLE
Subscript/superscript buttons do not remove formatting when calling it again

### ISSUE THREAD

**Issue by romanilchyshyn** [cjwirth/RichEditorView#69]
Problem can be solved by removing in normalize.css these lines: 

```
sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}
```

**Comment by cjwirth** [comment]
Hey! Thanks for catching this! 👍 

I haven't checked it, but how did you figure out this works? It'd be pretty cool if you wanted to make a pull request for this ⚡

**Comment by cjwirth** [comment]
Actually, it seems like just removing `vertical-align: baseline;` is enough, but then it makes the text kind of jump up and down when you make a subscript...

**Comment by romanilchyshyn** [comment]
@cjwirth Yes, but this 'text jumping' behaviour is the same as in [ZSSRichTextEditor](https://github.com/nnhubbard/ZSSRichTextEditor). And also we expect this behaviour when calling `document.execCommand('subscript', false, null)` without any css.

P.S.: I'm not web dev so i don't know the best solution here. Actually I found that with my friend's help using Chrome developer tools.

**Comment by cjwirth** [comment]
Just pushed this to the `develop` branch 👍 
Take a look!

**Comment by cjwirth** [comment]
Closing this issue, even though it's not merged to master yet.

Let me know what you think 😃 
If you're still having problems when using the `develop` branch, feel free to reopen the issue 👍

**Comment by romanilchyshyn** [comment]
There are some cases which can break subscript toggling. You can reproduce by steps:
1. Write some text in editor.
2. Push subscript button (without text selection). Write some subscripted text in editor.
3. Push underline button (without text selection). Write some underlined subscripted text in editor.
4. Push subscript button again (without text selection). As result we have subscript of subscripted text.

I don't know solution for this but it related with some special html tags placing when text is not selected. 
By the way this is very special and not critical issue.
