### ISSUE TITLE
Mentions and hashtags support

### ISSUE THREAD

**Issue by Deliany** [cjwirth/RichEditorView#72]
Are you planning to support mentions and hashtags? I mean fire event when user start typing word starting @ or # symbol or change caret position to such word and ability to replace(or insert) autocompleted mention or tag

**Comment by cjwirth** [comment]
Nope, that's something that I consider to be pretty domain-specific. Not everyone who uses this library will want or need that kind of functionality.

You're welcome to create a plugin or something, by making some custom JavaScript file and loading it, though! You might be able to get something working like that!
