### ISSUE TITLE
Extra scrolling space in editor

### ISSUE THREAD

**Issue by markbao** [cjwirth/RichEditorView#76]
Extra scrolling space exists in the editor. Is there any way to remove this? Perhaps there's a way to use JS to set the height of the editor to a max of the height of the view?

![extraspace](https://cloud.githubusercontent.com/assets/27594/16930001/2daf9212-4cef-11e6-8d22-da21f35eb374.gif)

**Comment by markbao** [comment]
Added screenshot.

**Comment by cjwirth** [comment]
That is weird. What does your setup look like to get this? 
I do most of the testing and dev in the sample app, and I don't think I've ever seen this 😅

**Comment by cjwirth** [comment]
Closing this because it's a year old. I'm not sure if it's still around. I added it to the superthread, so I'm going to close this one.
