### ISSUE TITLE
make  keyboard dismiss

### ISSUE THREAD

**Issue by NancyZY** [cjwirth/RichEditorView#78]
I want to dismiss the keyboard when I click the outside of RichEditorView, what should I do? I try to  
delegate the UITextViewDelegate's method touchesEnded(),but doesn't work

**Comment by cjwirth** [comment]
It will really depend on the setup of your views. You'll have to set up some kind of action on the other views that _aren't_ the RichEditorView. When you get notified that one of the other views has been tapped, you'll just have to tell the RichEditorView stop being the first responder, or blur, or one of those methods.

> I try to delegate the UITextViewDelegate's method touchesEnded(),but doesn't work

RichEditorView is not a UITextView, so anything with UITextViewDelegate won't do anything.

**Comment by NancyZY** [comment]
Sorry, I cannot totally understand this words :  tell the RichEditorView stop being the first responder. Can you explain it with some code. And there are some ways to custom  toolbar.options?  Like RichEditorOption.Header(Int) can combine one option, then expand the all header options As user needed. Thanks for your reply

**Comment by cjwirth** [comment]
> Sorry, I cannot totally understand this words : tell the RichEditorView stop being the first responder. 

Inputs that are currently focused (have the keyboard up) are called the "first responder" in iOS. When you make it resign first responder, it means that it stops showing the keyboard. Usually you can just call `inputView.resignFirstResponder()`, but that actually doesn't work with RichEditorView (I should make it so it does...)

You can call `editorView.blur()` to lose focus and close the keyboard though.

> And there are some ways to custom toolbar.options? Like RichEditorOption.Header(Int) can combine one option, then expand the all header options As user needed. 

No, you'd need to make your own custom keyboard for this. Everyone's UI requirements will be different, so the toolbar that I provided is really isn't much more than the simplest it can be, to give people a starting point to see how to expand on it and make their own.

**Comment by NancyZY** [comment]
Thanks for your  interpretion in detail, it help me a lot

**Comment by cjwirth** [comment]
Cool, no problem 👍
