### ISSUE TITLE
Change of background color

### ISSUE THREAD

**Issue by Jirka1111** [cjwirth/RichEditorView#8]
Hello,
I am pretty desperate. I just can't figure out how can I change background color of webview. It is white, I want a clear color.

**Comment by cjwirth** [comment]
Hey,

Sorry, the `setEditorBackgroundColor` changes the background color _inside_ the `UIWebView`. Maybe I can make this better, but it's not something I was thinking about.

In the meantime, this should work:
```
// editorView is a RichEditorView
editorView.backgroundColor = UIColor.clearColor()
editorView.webView.backgroundColor = UIColor.clearColor()
editorView.webView.opaque = false
```

I put it into the sample project after setting the editorView's delegate, and it worked just fine.

**Comment by Jirka1111** [comment]
Dear @cjwirth, this solution don't work in Swift 2.0. Do you have another solution?

Thanks in advance.

**Comment by cjwirth** [comment]
Ah, sorry, I forgot that the internal webivew was private. Try it on the _development_ branch and it should work.

**Comment by fukemy** [comment]
not working to me
