### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by terenzeyuen** [cjwirth/RichEditorView#82]
Can we create our own custom toolbar? For example toolbar with a popup like evernote..

![img_3724](https://cloud.githubusercontent.com/assets/2553680/18306139/624f1428-74e2-11e6-9e88-c553913c8b6b.PNG)

**Comment by terenzeyuen** [comment]
Thanks.

**Comment by RanjitKadam** [comment]
how to add spacing between buttons in existing tool bar?

Also if I want to create a custom toolbar , how should i proceed? I created a new class and xib but how to proceed further ? so that i can interact with buttons on my toolbar

**Comment by JordiGN** [comment]
Is there a way to call just a few options? or any way to call them all less one of them? and if you did the custom toolbar any suggestions? Thanks in advance

**Comment by cjwirth** [comment]
Yeah, it should be in the readme, just pass in the options you want to use:

```Swift
let toolbar = RichEditorToolbar(frame: CGRectMake(0, 0, 320, 44))
// To use all of them
toolbar.options = RichEditorOptions.all()
// To only use a few
toolbar.options = [.clear, .bold, .italic]
```

**Comment by ramohanreddy** [comment]
Hi , How to use custom buttons instead of Tool bar options.

**Comment by GermanVelibekovHouzz** [comment]
@cjwirth We try to put our `RichEditorTextView` inside `inputAccessoryView`. Is it possible?
