### ISSUE TITLE
support for swift 2.3

### ISSUE THREAD

**Issue by khs8727** [cjwirth/RichEditorView#86]
Please enable this library to support swift 2.3!
Thanks!

**Comment by joergsimon** [comment]
+1

**Comment by cjwirth** [comment]
Sorry for being so late, I've been doing a bit of traveling. I will get both Swift 2.3 and Swift 3 versions out this weekend.

**Comment by candostdagdeviren** [comment]
I opened a PR ( #87 ) for Swift 3 support. Also there is another one ( #85 ) for Swift 2.3 support.

**Comment by cjwirth** [comment]
Sorry it's been like 2 weeks. I have a [branch](https://github.com/cjwirth/RichEditorView/tree/swift-2.3) that you can use with Swift 3. Before releasing it, I just need to make sure the versions will be OK, update some version numbers, and then get it out. The Swift 2.3 version code won't actually change, so you can specify it directly in your Podfile if you want to upgrade right now.

**Comment by cjwirth** [comment]
I'm going to `notfix` Swift 2.3, but I did just merge Swift 3 into master (finally.....)
