### ISSUE TITLE
Question: Is there a reason clipsToBounds is set to false on the scrollView?

### ISSUE THREAD

**Issue by hernan43** [cjwirth/RichEditorView#9]
In the setup function for the RichEditorView class, the scrollView has its clipsToBounds property set to false:

https://github.com/cjwirth/RichEditorView/blob/master/RichEditorView/Classes/RichEditorView.swift#L153

This causes a problem for my particular usage of the RichEditorView. It causes the content in the editor to scroll over other controls I have in my view. If I set it to false it "fixes" the issue.

I'm not experienced enough with Swift/iOS programming to know if this will cause bizarre and unpredictable effects on other aspects of the RichEditorView. It *seems* to work fine, but I was curious if there was a larger reason to set clipsToBounds to false.

**Comment by cjwirth** [comment]
Yeah, unfortunately there is a reason for it. Might be able to take it out now, though. The reason it's there is the autocorrect popup: 

![](http://www.maclife.com/files/u332541/2014/12/howtoautocorrectmain.png)

With `clipsToBounds` set to true, that little popup will also get cutoff, unfortunately. 

There shouldn't be any other problems with getting rid of it though.

**Comment by hernan43** [comment]
Thanks!
