### ISSUE TITLE
`line-height` is hardcoded.

### ISSUE THREAD

**Issue by zummenix** [cjwirth/RichEditorView#92]
https://github.com/zummenix/RichEditorView/blob/319b26fba6fcf96ac6922af7dbd9e8779f115607/RichEditorView/Assets/editor/style.css#L61
Just curious whether we can safely remove it.

**Comment by zummenix** [comment]
Seems like we can't.
https://github.com/cjwirth/RichEditorView/blob/319b26fba6fcf96ac6922af7dbd9e8779f115607/RichEditorView/Classes/RichEditorView.swift#L488

**Comment by zummenix** [comment]
Is `RE.editor.clientHeight` reliable to get line height?

**Comment by cjwirth** [comment]
Yeah, this was a trade off to get the scrolling working well. This is another problem where I'm sure there is a better solution that I just don't know about. 

> Is `RE.editor.clientHeight` reliable to get line height?

I don't think so. IIRC, it is written the way it is, because I didn't know of a reliable way to get the line height...

**Comment by cjwirth** [comment]
This has been merged into the latest master branch. Thanks for your fixes 💪
