### ISSUE TITLE
Use UIImagePickerController insert Image from photo album

### ISSUE THREAD

**Issue by PlayApple** [cjwirth/RichEditorView#98]
I save image to ducoment and  path is  file:///var/mobile/Containers/Data/Application/6A26C23E-E084-40DF-80EB-5D41D5AC994A/Documents/test_image_name.jpg

I insert image to RichEditorView

A. image is ok
editorView.insertImage("file:///var/mobile/Containers/Data/Application/6A26C23E-E084-40DF-80EB-5D41D5AC994A/Documents/test_image_name.jpg", alt: "pic") 

B. image is not loaded
editorView.insertImage("test_image_name.jpg", alt: "pic") 

How can i insert image use image name? not image full path. 
Because documents path can be changed when Xcode build and install app.

Thank you!

**Comment by piechart** [comment]
Hi. How do you observe **didFinishPickingMediaWithInfo** to get those way (A) which as you telling inserts correctly?
I've tried different ways but nothing happens.

**Comment by cjwirth** [comment]
You're right, the path to the Documents directory changes when you restart your app.

You should never save the direct file URL to an image. Instead, you should be using the NSFileManager to get the location of the Documents directory, and then get the URL of your image file from inside there.

```Swift
let manager = FileManager.default
let directoryPaths = manager.urls(for: .documentDirectory, in: .userDomainMask)
let documetnsDirectory = directoryPaths[0].path
```

This should give you the path to the documents directory. I will leave finding your actual image inside the Documents directory as an exercise for the reader :)
